version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-loadbalancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pokemon
    ports:
      - "8080:8080"
  pokemon:
    image: pokemon:latest
#    ports:
#      - 8080:8080
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    labels:
      org.label-schema.group: "monitoring"


networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}